# Data Mining - A.A. 2025/2026
## Progetto Gruppo G3.3
### Membri:
- Masala Gabriele: 60/61/66245 (60/99/00004)
- Mantega Gabriele: 60/61/66251 (60/99/00006)
- Aresu Matteo: 60/99/00014

# 1 - Analisi del Dataset

In [1]:
# Dichiarazione Import
import pandas as pd
from sklearn import datasets
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
# Direttive di Pandas per avere un output più carino :3
pd.set_option('display.max_colwidth', 100)

# Caricamento DataFrame da sklearn
categories = ['rec.autos', 'rec.sport.baseball', 'sci.electronics', 'sci.med', 'sci.space']
train_dataset = datasets.fetch_20newsgroups(subset='train', categories=categories)
test_dataset = datasets.fetch_20newsgroups(subset='test', categories=categories)
X_train = pd.DataFrame(train_dataset.data).rename(columns={0: 'raw_text'})
y_train = pd.DataFrame(train_dataset.target).rename(columns={0: 'category'})

# Stampo la descrizione del dataset
print(train_dataset.DESCR[90:845])

The 20 newsgroups dataset comprises around 18000 newsgroups posts on
20 topics split in two subsets: one for training (or development)
and the other one for testing (or for performance evaluation). The split
between the train and test set is based upon a messages posted before
and after a specific date.

This module contains two loaders. The first one,
:func:`sklearn.datasets.fetch_20newsgroups`,
returns a list of the raw texts that can be fed to text feature
extractors such as :class:`~sklearn.feature_extraction.text.CountVectorizer`
with custom parameters so as to extract feature vectors.
The second one, :func:`sklearn.datasets.fetch_20newsgroups_vectorized`,
returns ready-to-use features, i.e., it is not necessary to use a feature
extractor.

In [3]:
# Stampo il Training Set
display(X_train)

# Stampo il Test Set
display(y_train)

                                                                                                 raw_text
0     From: wright@duca.hi.com (David Wright)\nSubject: Re: NATURAL ANTI-cancer/AIDS Remedies\nOrganiz...
1     From: tedward@cs.cornell.edu (Edward [Ted] Fischer)\nSubject: Re: DAVE KINGMAN FOR THE HALL OF F...
2     Subject: al stats\nFrom: "michael mcguire" <michael.mcguire@canrem.com>\nReply-To: "michael mcgu...
3     From: daubendr@NeXTwork.Rose-Hulman.Edu (Darren R Daubenspeck)\nSubject: Re: Plymouth Sundance/D...
4     From: ddr@flux.isr.alaska.edu (Donald D Rice)\nSubject: Heavy-duty antenna simulation software\n...
...                                                                                                   ...
2964  From: mont@netcom.com (Mont Pierce)\nSubject: Re: 8051 Microcontroller\nOrganization: Netcom - O...
2965  From: jimf@centerline.com (Jim Frost)\nSubject: Re: WARNING.....(please read)...\nOrganization: ...
2966  From: m-it2691@DOC.CS.NYU.EDU (Tim Tsai)\nSubject: AWD BMW\nLines: 11\nX-Received: by usenet.pa....
2967  From: chris@alien.saar.de (Christian Reisel)\nDistribution: world\nOrganization: Chaos live\nSub...
2968  From: homer@tripos.com (Webster Homer)\nSubject: Mind Machines?\nSummary: Do mind machines work?...

[2969 rows x 1 columns]

      category
0            3
1            1
2            1
3            0
4            2
...        ...
2964         2
2965         0
2966         0
2967         2
2968         3

[2969 rows x 1 columns]

In [7]:
# Stampo a schermo il primo record del Dataset
print(X_train['raw_text'][0])

From: wright@duca.hi.com (David Wright)
Subject: Re: NATURAL ANTI-cancer/AIDS Remedies
Organization: Hitachi Computer Products, OSSD division
Lines: 16
NNTP-Posting-Host: duca.hi.com

In article <19604@pitt.UUCP> geb@cs.pitt.edu (Gordon Banks) writes:
|In article <1993Apr6.165840.5703@cnsvax.uwec.edu> mcelwre@cnsvax.uwec.edu writes:
|>     The biggest reason why the cost of medical care is so EXTREMELY high and
|>increasing is that NATURAL methods of treatment and even diagnosis are still
|>being SYSTEMATICALLY IGNORED and SUPPRESSED by the MONEY-GRUBBING and POWER-
|>MONGERING "medical" establishment.

|That's not the half of it.  Did you realize that all medical doctors have
|now been replaced by aliens?

Yup.  By the way, what planet are you from, and once you got here, did
you encounter those prejudices against foreign medical graduates?

  -- David Wright, Hitachi Computer Products (America), Inc.  Waltham, MA
     wright@hicomb.hi.com  ::  These are my opinions, not necessarily
     Hitachi's, though they are the opinions of all right-thinking people

# 2 - Preprocessing

In [5]:
# Utilizzo la classe TfidfVectorizer per convertire i record testuali in record numerici
tfidf_vectorizer = TfidfVectorizer(stoAp_words='english', max_features=100)
tfidf_vectorizer.fit_transform(X_train)

TypeError: TfidfVectorizer.__init__() got an unexpected keyword argument 'stoAp_words'